# Integrate Oracle Libraries (use by oracledb at build)
echo OCI_xxx_xxx
echo ${OCI_LIB_DIR}
echo ${OCI_INC_DIR}
export OCI_LIB_DIR=/u01/app/oracle/product/11.2.0/xe/lib
export OCI_INC_DIR=/u01/app/oracle/product/11.2.0/xe/rdbms/public

# Integrate Oracle Libraries (use by oracledb at execution)
echo LD_LIBRARY_PATH
echo ${LD_LIBRARY_PATH}
echo $USER

export LD_LIBRARY_PATH=/u01/app/oracle/product/11.2.0/xe/lib/:$LD_LIBRARY_PATH 
sudo ldconfig


# Create User for integrations tests
"$ORACLE_HOME/bin/sqlplus" -L -S / AS SYSDBA <<SQL
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY welcome;
SQL

# Create User for integrations tests
"$ORACLE_HOME/bin/sqlplus" -L -S / AS SYSDBA <<SQL
CREATE USER SEQUELIZE
  IDENTIFIED BY test
  DEFAULT TABLESPACE SYSAUX
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for SEQUELIZE 
  GRANT CONNECT TO SEQUELIZE;
  GRANT AUTHENTICATEDUSER TO SEQUELIZE;
  ALTER USER SEQUELIZE DEFAULT ROLE NONE;
  -- 18 System Privileges for SEQUELIZE 
  GRANT CREATE ANY TYPE TO SEQUELIZE;
  GRANT CREATE ANY TRIGGER TO SEQUELIZE;
  GRANT CREATE VIEW TO SEQUELIZE;
  GRANT CREATE SYNONYM TO SEQUELIZE;
  GRANT CREATE TABLESPACE TO SEQUELIZE;
  GRANT CREATE ANY INDEXTYPE TO SEQUELIZE;
  GRANT CREATE ANY SEQUENCE TO SEQUELIZE;
  GRANT CREATE ANY MATERIALIZED VIEW TO SEQUELIZE;
  GRANT CREATE TYPE TO SEQUELIZE;
  GRANT CREATE SEQUENCE TO SEQUELIZE;
  GRANT CREATE ANY INDEX TO SEQUELIZE;
  GRANT CREATE ANY TABLE TO SEQUELIZE;
  GRANT CREATE TABLE TO SEQUELIZE;
  GRANT CREATE SESSION TO SEQUELIZE;
  GRANT CREATE TRIGGER TO SEQUELIZE;
  GRANT CREATE ANY PROCEDURE TO SEQUELIZE;
  GRANT CREATE ANY VIEW TO SEQUELIZE;
  GRANT CREATE ANY SYNONYM TO SEQUELIZE;
  -- 1 Tablespace Quota for SEQUELIZE 
  ALTER USER SEQUELIZE QUOTA UNLIMITED ON SYSAUX;
SQL
